import { useState, useMemo } from 'react';
import {
  Printer,
  Copy,
  Check,
  ShieldCheck,
  Download,
  Award,
} from 'lucide-react';
import { MOCK_CASES } from '../data/mockCases';
import { MOCK_EVIDENCE } from '../data/mockEvidence';
import { MOCK_DETECTIONS } from '../data/mockInvestigation';
import { Button, MonoLabel } from '../components/ui/primitives';
import { formatDateTime, formatFileSize } from '../utils/format';

type ReportType = 'section65b' | 'dossier' | 'custody';

export function ReportsPage() {
  const [selectedCaseId, setSelectedCaseId] = useState<string>(MOCK_CASES[0].id);
  const [reportType, setReportType] = useState<ReportType>('section65b');
  const [copied, setCopied] = useState(false);

  // Active case
  const activeCase = useMemo(() => {
    return MOCK_CASES.find((c) => c.id === selectedCaseId) ?? MOCK_CASES[0];
  }, [selectedCaseId]);

  // Evidence for this case
  const caseEvidence = useMemo(() => {
    return MOCK_EVIDENCE.filter((e) => e.caseId === selectedCaseId);
  }, [selectedCaseId]);

  // Detections / exhibits for this case
  const caseDetections = useMemo(() => {
    return MOCK_DETECTIONS.filter((d) => d.caseId === selectedCaseId);
  }, [selectedCaseId]);

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(reportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeCase.id}_Forensic_Report_${reportType}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Generate plain report content for copy/export
  const reportContent = useMemo(() => {
    const timestamp = new Date().toUTCString();
    const divider = '='.repeat(80);

    if (reportType === 'section65b') {
      return `${divider}
       FORENSIC-X COURT EVIDENCE CERTIFICATE OF AUTHENTICITY
   Pursuant to Section 65B Indian Evidence Act / Section 63 BSA & ISO/IEC 27037
${divider}
Generated: ${timestamp}
Report Reference: 65B-FX-${activeCase.id}-${Date.now().toString().slice(-6)}

CASE DETAILS:
- Case Identifier:   ${activeCase.id}
- Case Title:        ${activeCase.title}
- Lead Investigator: ${activeCase.investigator}
- Total Exhibits:    ${caseEvidence.length}

EXHIBIT HASH MANIFEST:
${caseEvidence
  .map(
    (ev, idx) => `
[EXHIBIT #${idx + 1}] ${ev.id} — ${ev.filename}
  Channel:       ${ev.cameraChannel} (${ev.location})
  Hardware:      ${ev.deviceModel} (${ev.deviceType.toUpperCase()})
  SHA-256 Hash:  ${ev.sha256}
  Integrity:     VERIFIED UNTAMPERED (CRC & Watermark Intact)
  Collection:    ${formatDateTime(ev.collectionTime)} by ${ev.collectionOfficer}`
  )
  .join('\n')}

INVESTIGATION AI SIGHTINGS & EXHIBIT HIGHLIGHTS:
${caseDetections
  .map(
    (det, idx) => `
[SIGHTING #${idx + 1}] ${det.id} (${det.targetType.toUpperCase()})
  Time (Calibrated): ${formatDateTime(det.calibratedTimestamp)}
  Channel/Loc:       ${det.cameraChannel} [${det.cameraLocation}]
  Classification:    ${det.label} (Confidence: ${(det.confidence * 100).toFixed(1)}%)
  Frame Snapshot:    ${det.sha256Snapshot}`
  )
  .join('\n')}

CERTIFICATION DECLARATION:
I, ${activeCase.investigator}, hereby certify under Section 65B of the Indian Evidence Act
that the digital video recordings detailed above were captured by surveillance systems
during their ordinary lawful operations, and cryptographic hashing has verified that no
tampering, splicing, or alteration has occurred.
${divider}`;
    }

    return `${divider}
           FORENSIC CASE INVESTIGATION DOSSIER
${divider}
Case ID: ${activeCase.id}
Title:   ${activeCase.title}
Status:  ${activeCase.status.toUpperCase()}
Generated by: FORENSIC-X Digital Investigation Platform on ${timestamp}

Summary:
${activeCase.description}

Key Registered Evidence:
${caseEvidence.map((e) => `- ${e.id}: ${e.filename} (${formatFileSize(e.fileSize)}, SHA-256: ${e.sha256})`).join('\n')}
${divider}`;
  }, [activeCase, caseEvidence, caseDetections, reportType]);

  return (
    <div className="max-w-screen-xl mx-auto px-6 pb-24">
      {/* ── Header ── */}
      <div className="pt-8 pb-6 border-b border-border-subtle flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Award size={16} className="text-accent" />
            <span className="text-2xs font-mono uppercase tracking-widest text-text-tertiary">
              Admissibility & Audit
            </span>
          </div>
          <h1 className="text-2xl font-bold text-text-primary tracking-tight font-mono">
            Court Forensic Reports & 65B Certificates
          </h1>
          <p className="text-xs text-text-secondary mt-1">
            Generate legally compliant digital evidence certificates under Section 65B Indian Evidence Act / Section 63 BSA.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Button variant="secondary" size="sm" icon={<Printer size={13} />} onClick={handlePrint}>
            Print / PDF
          </Button>
          <Button variant="secondary" size="sm" icon={copied ? <Check size={13} /> : <Copy size={13} />} onClick={handleCopy}>
            {copied ? 'Copied' : 'Copy Text'}
          </Button>
          <Button variant="primary" size="sm" icon={<Download size={13} />} onClick={handleDownload}>
            Export TXT
          </Button>
        </div>
      </div>

      {/* ── Case & Report Controls ── */}
      <div className="bg-surface-01 border border-border-subtle rounded-xl p-4 mb-6 flex flex-col md:flex-row items-center justify-between gap-4">
        {/* Case selector */}
        <div className="flex items-center gap-3 w-full md:w-auto">
          <span className="text-xs font-mono uppercase text-text-tertiary">Case:</span>
          <select
            value={selectedCaseId}
            onChange={(e) => setSelectedCaseId(e.target.value)}
            className="bg-surface-base border border-border-subtle rounded-lg px-3 py-2 text-xs text-text-primary font-mono focus:border-accent"
          >
            {MOCK_CASES.map((c) => (
              <option key={c.id} value={c.id}>
                {c.id} — {c.title}
              </option>
            ))}
          </select>
        </div>

        {/* Report type pills */}
        <div className="flex items-center gap-2 w-full md:w-auto overflow-x-auto">
          {[
            { id: 'section65b', label: 'Section 65B Certificate' },
            { id: 'dossier', label: 'Incident Dossier' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setReportType(tab.id as ReportType)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
                reportType === tab.id
                  ? 'bg-accent text-white border-accent shadow-sm'
                  : 'bg-surface-base text-text-secondary border-border-subtle hover:text-text-primary'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* ── Printed Certificate Paper Preview ── */}
      <div className="bg-surface-01 border border-border-subtle rounded-2xl p-8 shadow-card space-y-8 font-sans">
        {/* Document Header Seal */}
        <div className="text-center pb-6 border-b border-border-subtle">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-accent-dim border border-accent/30 text-accent mb-3">
            <ShieldCheck size={24} />
          </div>
          <h2 className="text-xl font-bold font-mono tracking-tight text-text-primary uppercase">
            Certificate of Digital Evidence Authenticity
          </h2>
          <p className="text-2xs font-mono text-text-tertiary mt-1">
            Section 65B of Indian Evidence Act, 1872 / Section 63 Bharatiya Sakshya Adhiniyam, 2023 & ISO/IEC 27037:2012
          </p>
        </div>

        {/* Case & Jurisdiction Info */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          <div className="p-3.5 rounded-lg bg-surface-base border border-border-subtle">
            <span className="text-3xs font-mono text-text-tertiary block">PROCEEDINGS / CASE ID</span>
            <span className="font-mono font-bold text-accent text-sm">{activeCase.id}</span>
            <p className="text-text-secondary mt-0.5">{activeCase.title}</p>
          </div>

          <div className="p-3.5 rounded-lg bg-surface-base border border-border-subtle">
            <span className="text-3xs font-mono text-text-tertiary block">CERTIFYING INVESTIGATOR</span>
            <span className="font-semibold text-text-primary text-sm">{activeCase.investigator}</span>
            <p className="text-text-secondary mt-0.5">Senior Cyber Forensics Officer</p>
          </div>

          <div className="p-3.5 rounded-lg bg-surface-base border border-border-subtle">
            <span className="text-3xs font-mono text-text-tertiary block">HASH ALGORITHM</span>
            <span className="font-mono font-semibold text-green text-sm">SHA-256 (FIPS 180-4)</span>
            <p className="text-text-secondary mt-0.5">Tamper Proof Verification: Intact</p>
          </div>
        </div>

        {/* Evidence Manifest Table */}
        <div>
          <h3 className="text-xs font-mono uppercase text-text-tertiary tracking-wider mb-3">
            1. Digital Evidence Manifest & Hash Verification
          </h3>
          <div className="border border-border-subtle rounded-xl overflow-hidden">
            <table className="w-full text-left text-xs">
              <thead className="bg-surface-02 font-mono text-2xs text-text-secondary border-b border-border-subtle">
                <tr>
                  <th className="py-2.5 px-4">Exhibit ID</th>
                  <th className="py-2.5 px-4">File Name</th>
                  <th className="py-2.5 px-4">Camera Channel</th>
                  <th className="py-2.5 px-4">Size</th>
                  <th className="py-2.5 px-4">SHA-256 Hash Digest</th>
                  <th className="py-2.5 px-4">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border-subtle font-mono text-2xs">
                {caseEvidence.map((ev) => (
                  <tr key={ev.id} className="hover:bg-surface-02/50 transition-colors">
                    <td className="py-3 px-4 text-accent font-bold">{ev.id}</td>
                    <td className="py-3 px-4 font-sans text-text-primary">{ev.filename}</td>
                    <td className="py-3 px-4 text-text-secondary">{ev.cameraChannel}</td>
                    <td className="py-3 px-4 text-text-secondary">{formatFileSize(ev.fileSize)}</td>
                    <td className="py-3 px-4 text-3xs text-text-tertiary max-w-xs truncate">
                      {ev.sha256}
                    </td>
                    <td className="py-3 px-4">
                      <span className="px-2 py-0.5 rounded bg-green-dim text-green font-semibold">
                        Verified
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* AI Sightings & Exhibit Timeline */}
        <div>
          <h3 className="text-xs font-mono uppercase text-text-tertiary tracking-wider mb-3">
            2. Correlated Target Sightings & Frame Snapshots
          </h3>
          <div className="space-y-2">
            {caseDetections.map((det) => (
              <div
                key={det.id}
                className="p-3 rounded-lg bg-surface-base border border-border-subtle flex items-center justify-between gap-4 text-xs"
              >
                <div>
                  <div className="flex items-center gap-2 mb-0.5">
                    <MonoLabel className="text-accent">{det.id}</MonoLabel>
                    <span className="font-semibold text-text-primary">{det.label}</span>
                    <span className="font-mono text-3xs px-1.5 py-0.2 rounded bg-surface-02 text-text-secondary">
                      Conf: {(det.confidence * 100).toFixed(0)}%
                    </span>
                  </div>
                  <p className="text-2xs text-text-secondary">
                    {det.cameraChannel} ({det.cameraLocation}) • Calibrated Time: {formatDateTime(det.calibratedTimestamp)}
                  </p>
                </div>
                <div className="text-right font-mono text-3xs text-text-tertiary shrink-0">
                  <span>Frame Hash: {det.sha256Snapshot.slice(0, 16)}...</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Sign-off & Stamp */}
        <div className="pt-8 border-t border-border-subtle flex flex-col md:flex-row items-end justify-between gap-6">
          <div className="max-w-md text-2xs text-text-tertiary leading-relaxed">
            This certificate is system-generated by FORENSIC-X Digital Forensic Evidence Suite.
            Cryptographic signatures and hashes adhere to NIST FIPS 180-4 guidelines.
          </div>

          <div className="border border-border-subtle rounded-xl p-4 bg-surface-base w-64 text-center">
            <div className="h-14 flex items-center justify-center text-accent/80 font-mono text-xs italic">
              [ Digitally Signed by {activeCase.investigator} ]
            </div>
            <div className="border-t border-border-subtle pt-2">
              <p className="text-xs font-semibold text-text-primary">{activeCase.investigator}</p>
              <p className="text-3xs text-text-tertiary font-mono">Investigating Officer Seal</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
